// このファイルは自動生成です。VS Code本体(microsoft/vscode, MITライセンス)の
// extensions/theme-seti/icons/vs-seti-icon-theme.json から抽出して作成した
// (VS Codeを新規インストールした直後の既定のファイルアイコンテーマ"Seti"
// そのもの)。charはこのフォント(public/fonts/seti.woff、同じくVS Code本体
// からそのまま取得)のグリフ文字(Private Use Area、そのままでは通常
// 表示されず、seti.woffを適用した要素の中でだけ意味のある絵に変わる)。
// 生成元:
// https://github.com/microsoft/vscode/blob/main/extensions/theme-seti/icons/vs-seti-icon-theme.json
//
// 注意: 元のJSONにはfileExtensions(拡張子)・fileNames(ファイル名)に加え
// languageIds(VS Codeが検出した言語ID)による解決もある。実は.py/.js/.ts/
// .html/.css/.json/.md/.go/.rs/.java等の非常にメジャーな拡張子の大半は
// fileExtensionsには载っておらず、languageIds経由でしか解決されない
// (VS Code側は各言語の同梱拡張機能が持つ拡張子→言語IDの対応を経由する -
// この対応自体はtheme-seti自身のJSONには含まれない)。そのため主要な拡張子に
// ついてはSETI_EXTENSION_TO_ICON_VIA_LANGUAGEとして本ファイルの生成時に
// あらかじめ「拡張子 -> languageId -> アイコンID」を解決した結果を補っている。

export interface SetiIconDefinition {
    char: string;
    color: string;
}

export const SETI_DEFAULT_ICON_ID = "_default";

// アイコンID -> フォントグリフ文字 + 色
export const SETI_ICON_DEFINITIONS: Record<string, SetiIconDefinition> = {
    "_R": { char: "", color: "#519aba" },
    "_argdown": { char: "", color: "#519aba" },
    "_asm": { char: "", color: "#cc3e44" },
    "_audio": { char: "", color: "#a074c4" },
    "_babel": { char: "", color: "#cbcb41" },
    "_bazel": { char: "", color: "#8dc149" },
    "_bazel_1": { char: "", color: "#4d5a5e" },
    "_bicep": { char: "", color: "#519aba" },
    "_bower": { char: "", color: "#e37933" },
    "_bsl": { char: "", color: "#cc3e44" },
    "_c": { char: "", color: "#519aba" },
    "_c-sharp": { char: "", color: "#519aba" },
    "_c_1": { char: "", color: "#a074c4" },
    "_c_2": { char: "", color: "#cbcb41" },
    "_cake": { char: "", color: "#cc3e44" },
    "_cake_php": { char: "", color: "#cc3e44" },
    "_clock": { char: "", color: "#519aba" },
    "_clock_1": { char: "", color: "#6d8086" },
    "_clojure": { char: "", color: "#8dc149" },
    "_clojure_1": { char: "", color: "#519aba" },
    "_code-climate": { char: "", color: "#8dc149" },
    "_coffee": { char: "", color: "#cbcb41" },
    "_coldfusion": { char: "", color: "#519aba" },
    "_config": { char: "", color: "#6d8086" },
    "_cpp": { char: "", color: "#519aba" },
    "_cpp_1": { char: "", color: "#a074c4" },
    "_cpp_2": { char: "", color: "#cbcb41" },
    "_crystal": { char: "", color: "#d4d7d6" },
    "_crystal_embedded": { char: "", color: "#d4d7d6" },
    "_css": { char: "", color: "#519aba" },
    "_csv": { char: "", color: "#8dc149" },
    "_cu_1": { char: "", color: "#a074c4" },
    "_d": { char: "", color: "#cc3e44" },
    "_dart": { char: "", color: "#519aba" },
    "_db": { char: "", color: "#f55385" },
    "_db_1": { char: "", color: "#519aba" },
    "_default": { char: "", color: "#d4d7d6" },
    "_docker": { char: "", color: "#519aba" },
    "_docker_1": { char: "", color: "#4d5a5e" },
    "_docker_2": { char: "", color: "#8dc149" },
    "_ejs": { char: "", color: "#cbcb41" },
    "_elixir": { char: "", color: "#a074c4" },
    "_elixir_script": { char: "", color: "#a074c4" },
    "_elm": { char: "", color: "#519aba" },
    "_eslint": { char: "", color: "#a074c4" },
    "_eslint_1": { char: "", color: "#4d5a5e" },
    "_ethereum": { char: "", color: "#519aba" },
    "_favicon": { char: "", color: "#cbcb41" },
    "_firebase": { char: "", color: "#e37933" },
    "_firefox": { char: "", color: "#e37933" },
    "_font": { char: "", color: "#cc3e44" },
    "_git": { char: "", color: "#41535b" },
    "_github": { char: "", color: "#d4d7d6" },
    "_gitlab": { char: "", color: "#e37933" },
    "_go": { char: "", color: "#519aba" },
    "_go2": { char: "", color: "#519aba" },
    "_godot": { char: "", color: "#519aba" },
    "_godot_1": { char: "", color: "#cc3e44" },
    "_godot_2": { char: "", color: "#cbcb41" },
    "_godot_3": { char: "", color: "#a074c4" },
    "_gradle": { char: "", color: "#519aba" },
    "_grails": { char: "", color: "#8dc149" },
    "_graphql": { char: "", color: "#f55385" },
    "_grunt": { char: "", color: "#e37933" },
    "_gulp": { char: "", color: "#cc3e44" },
    "_hacklang": { char: "", color: "#e37933" },
    "_haml": { char: "", color: "#cc3e44" },
    "_happenings": { char: "", color: "#519aba" },
    "_haskell": { char: "", color: "#a074c4" },
    "_haxe": { char: "", color: "#e37933" },
    "_haxe_1": { char: "", color: "#cbcb41" },
    "_haxe_2": { char: "", color: "#519aba" },
    "_haxe_3": { char: "", color: "#a074c4" },
    "_heroku": { char: "", color: "#a074c4" },
    "_hex": { char: "", color: "#cc3e44" },
    "_html": { char: "", color: "#519aba" },
    "_html_1": { char: "", color: "#8dc149" },
    "_html_2": { char: "", color: "#cbcb41" },
    "_html_3": { char: "", color: "#e37933" },
    "_html_erb": { char: "", color: "#cc3e44" },
    "_ignored": { char: "", color: "#41535b" },
    "_illustrator": { char: "", color: "#cbcb41" },
    "_image": { char: "", color: "#a074c4" },
    "_info": { char: "", color: "#519aba" },
    "_ionic": { char: "", color: "#519aba" },
    "_jade": { char: "", color: "#cc3e44" },
    "_java": { char: "", color: "#cc3e44" },
    "_java_1": { char: "", color: "#519aba" },
    "_javascript": { char: "", color: "#cbcb41" },
    "_javascript_1": { char: "", color: "#e37933" },
    "_javascript_2": { char: "", color: "#519aba" },
    "_jenkins": { char: "", color: "#cc3e44" },
    "_jinja": { char: "", color: "#cc3e44" },
    "_json": { char: "", color: "#cbcb41" },
    "_json_1": { char: "", color: "#8dc149" },
    "_julia": { char: "", color: "#a074c4" },
    "_karma": { char: "", color: "#8dc149" },
    "_kotlin": { char: "", color: "#e37933" },
    "_less": { char: "", color: "#519aba" },
    "_license": { char: "", color: "#cbcb41" },
    "_license_1": { char: "", color: "#e37933" },
    "_license_2": { char: "", color: "#cc3e44" },
    "_liquid": { char: "", color: "#8dc149" },
    "_livescript": { char: "", color: "#519aba" },
    "_lock": { char: "", color: "#8dc149" },
    "_lua": { char: "", color: "#519aba" },
    "_makefile": { char: "", color: "#e37933" },
    "_makefile_1": { char: "", color: "#a074c4" },
    "_makefile_2": { char: "", color: "#6d8086" },
    "_makefile_3": { char: "", color: "#519aba" },
    "_markdown": { char: "", color: "#519aba" },
    "_maven": { char: "", color: "#cc3e44" },
    "_mdo": { char: "", color: "#cc3e44" },
    "_mustache": { char: "", color: "#e37933" },
    "_nim": { char: "", color: "#cbcb41" },
    "_notebook": { char: "", color: "#519aba" },
    "_npm": { char: "", color: "#41535b" },
    "_npm_1": { char: "", color: "#cc3e44" },
    "_npm_ignored": { char: "", color: "#41535b" },
    "_nunjucks": { char: "", color: "#8dc149" },
    "_ocaml": { char: "", color: "#e37933" },
    "_odata": { char: "", color: "#e37933" },
    "_pddl": { char: "", color: "#a074c4" },
    "_pdf": { char: "", color: "#cc3e44" },
    "_perl": { char: "", color: "#519aba" },
    "_photoshop": { char: "", color: "#519aba" },
    "_php": { char: "", color: "#a074c4" },
    "_pipeline": { char: "", color: "#e37933" },
    "_plan": { char: "", color: "#8dc149" },
    "_platformio": { char: "", color: "#e37933" },
    "_powershell": { char: "", color: "#519aba" },
    "_prisma": { char: "", color: "#519aba" },
    "_prolog": { char: "", color: "#e37933" },
    "_puppet": { char: "", color: "#cbcb41" },
    "_purescript": { char: "", color: "#d4d7d6" },
    "_python": { char: "", color: "#519aba" },
    "_react": { char: "", color: "#519aba" },
    "_react_1": { char: "", color: "#e37933" },
    "_reasonml": { char: "", color: "#cc3e44" },
    "_rescript": { char: "", color: "#cc3e44" },
    "_rescript_1": { char: "", color: "#f55385" },
    "_rollup": { char: "", color: "#cc3e44" },
    "_ruby": { char: "", color: "#cc3e44" },
    "_rust": { char: "", color: "#6d8086" },
    "_salesforce": { char: "", color: "#519aba" },
    "_sass": { char: "", color: "#f55385" },
    "_sbt": { char: "", color: "#519aba" },
    "_scala": { char: "", color: "#cc3e44" },
    "_shell": { char: "", color: "#8dc149" },
    "_slim": { char: "", color: "#e37933" },
    "_smarty": { char: "", color: "#cbcb41" },
    "_spring": { char: "", color: "#8dc149" },
    "_stylelint": { char: "", color: "#d4d7d6" },
    "_stylelint_1": { char: "", color: "#4d5a5e" },
    "_stylus": { char: "", color: "#8dc149" },
    "_sublime": { char: "", color: "#e37933" },
    "_svelte": { char: "", color: "#cc3e44" },
    "_svg": { char: "", color: "#a074c4" },
    "_svg_1": { char: "", color: "#519aba" },
    "_swift": { char: "", color: "#e37933" },
    "_terraform": { char: "", color: "#a074c4" },
    "_tex_1": { char: "", color: "#cbcb41" },
    "_tex_2": { char: "", color: "#e37933" },
    "_tex_3": { char: "", color: "#d4d7d6" },
    "_todo": { char: "", color: "#8a8a8a" },
    "_tsconfig": { char: "", color: "#519aba" },
    "_twig": { char: "", color: "#8dc149" },
    "_typescript": { char: "", color: "#519aba" },
    "_typescript_1": { char: "", color: "#e37933" },
    "_vala": { char: "", color: "#6d8086" },
    "_video": { char: "", color: "#f55385" },
    "_vite": { char: "", color: "#cbcb41" },
    "_vue": { char: "", color: "#8dc149" },
    "_wasm": { char: "", color: "#a074c4" },
    "_wat": { char: "", color: "#a074c4" },
    "_webpack": { char: "", color: "#519aba" },
    "_wgt": { char: "", color: "#519aba" },
    "_windows": { char: "", color: "#519aba" },
    "_word": { char: "", color: "#519aba" },
    "_xls": { char: "", color: "#8dc149" },
    "_xml": { char: "", color: "#e37933" },
    "_yarn": { char: "", color: "#519aba" },
    "_yml": { char: "", color: "#a074c4" },
    "_zig": { char: "", color: "#e37933" },
    "_zip": { char: "", color: "#cc3e44" },
    "_zip_1": { char: "", color: "#6d8086" },
};

// 拡張子(ドット無し・小文字、"spec.ts"のような複合拡張子も含む) -> アイコンID
// (VS Code本体のfileExtensions、拡張子ごとの特別なアイコン)
export const SETI_FILE_EXTENSIONS: Record<string, string> = {
    "3dm": "_svg_1",
    "3ds": "_svg_1",
    "ad": "_argdown",
    "ai": "_illustrator",
    "apex": "_salesforce",
    "argdown": "_argdown",
    "article": "_go",
    "asax": "_html_2",
    "ascx": "_html_1",
    "asm": "_asm",
    "aspx": "_html",
    "avi": "_video",
    "avif": "_image",
    "babelrc": "_babel",
    "babelrc.cjs": "_babel",
    "babelrc.js": "_babel",
    "bazel": "_bazel",
    "bazelignore": "_bazel",
    "bazelrc": "_bazel_1",
    "bazelversion": "_bazel",
    "bicep": "_bicep",
    "bowerrc": "_bower",
    "bsl": "_bsl",
    "build": "_bazel",
    "bzl": "_bazel",
    "cake": "_cake",
    "cer": "_lock",
    "cert": "_lock",
    "cfc": "_coldfusion",
    "cfm": "_coldfusion",
    "cjs.map": "_javascript",
    "cjsx": "_react",
    "class": "_java_1",
    "classpath": "_java",
    "cls": "_salesforce",
    "cmx": "_ocaml",
    "cmxa": "_ocaml",
    "codeclimate.yml": "_code-climate",
    "component": "_html_3",
    "config": "_config",
    "cr": "_crystal",
    "crt": "_lock",
    "cson": "_json",
    "css.map": "_css",
    "csv": "_csv",
    "ctp": "_cake_php",
    "cuh": "_cu_1",
    "d": "_d",
    "dae": "_svg_1",
    "direnv": "_config",
    "doc": "_word",
    "dockerignore": "_docker_1",
    "docx": "_word",
    "ds_store": "_ignored",
    "dtx": "_tex_2",
    "ecr": "_crystal_embedded",
    "edn": "_clojure_1",
    "ejs": "_ejs",
    "elm": "_elm",
    "eot": "_font",
    "epp": "_puppet",
    "erb": "_html_erb",
    "erb.html": "_html_erb",
    "es": "_javascript",
    "es5": "_javascript",
    "es7": "_javascript",
    "eslintignore": "_eslint_1",
    "eslintrc": "_eslint",
    "eslintrc.cjs": "_eslint",
    "eslintrc.js": "_eslint",
    "eslintrc.json": "_eslint",
    "eslintrc.yaml": "_eslint",
    "eslintrc.yml": "_eslint",
    "ex": "_elixir",
    "exs": "_elixir_script",
    "firebaserc": "_firebase",
    "flac": "_audio",
    "gd": "_godot",
    "gif": "_image",
    "gitattributes": "_git",
    "gitconfig": "_git",
    "github-issues": "_github",
    "gitkeep": "_git",
    "gitlab-ci.yml": "_gitlab",
    "gitmodules": "_git",
    "godot": "_godot_1",
    "gql": "_graphql",
    "gradle": "_gradle",
    "graphql": "_graphql",
    "graphqls": "_graphql",
    "gsp": "_grails",
    "h": "_c_1",
    "h++": "_cpp_1",
    "hack": "_hacklang",
    "haml": "_haml",
    "happenings": "_happenings",
    "hh": "_cpp_1",
    "hpp": "_cpp_1",
    "hs": "_haskell",
    "htaccess": "_config",
    "html.erb": "_html_erb",
    "hu": "_cu_1",
    "hx": "_haxe",
    "hxml": "_haxe_3",
    "hxp": "_haxe_2",
    "hxs": "_haxe_1",
    "hxx": "_cpp_1",
    "ico": "_favicon",
    "ins": "_tex_3",
    "ipynb": "_notebook",
    "jade": "_jade",
    "jar": "_zip",
    "jinja": "_jinja",
    "jinja2": "_jinja",
    "jpeg": "_image",
    "jpg": "_image",
    "js.map": "_javascript",
    "jscsrc": "_javascript_2",
    "jshintrc": "_javascript_2",
    "key": "_lock",
    "kt": "_kotlin",
    "kts": "_kotlin",
    "lhs": "_haskell",
    "liquid": "_liquid",
    "litcoffee": "_coffee",
    "ls": "_livescript",
    "master": "_html_2",
    "mdo": "_mdo",
    "mjs.map": "_javascript",
    "ml": "_ocaml",
    "mli": "_ocaml",
    "mov": "_video",
    "mp3": "_audio",
    "mp4": "_video",
    "mpg": "_video",
    "mustache": "_mustache",
    "nim": "_nim",
    "nims": "_nim",
    "nj": "_nunjucks",
    "njk": "_nunjucks",
    "njs": "_nunjucks",
    "npm-debug.log": "_npm",
    "npmignore": "_npm_1",
    "npmrc": "_npm_1",
    "nunj": "_nunjucks",
    "nunjs": "_nunjucks",
    "nunjucks": "_nunjucks",
    "obj": "_svg_1",
    "odata": "_odata",
    "ogg": "_audio",
    "ogv": "_video",
    "otf": "_font",
    "pddl": "_pddl",
    "pdf": "_pdf",
    "pem": "_lock",
    "php.inc": "_php",
    "pipeline": "_pipeline",
    "plan": "_plan",
    "png": "_image",
    "pp": "_puppet",
    "prisma": "_prisma",
    "pro": "_prolog",
    "psd": "_photoshop",
    "purs": "_purescript",
    "pxm": "_image",
    "r": "_R",
    "re": "_reasonml",
    "res": "_rescript",
    "resi": "_rescript_1",
    "rmd": "_R",
    "s": "_asm",
    "sass": "_sass",
    "sbt": "_sbt",
    "scala": "_scala",
    "slang": "_crystal_embedded",
    "slide": "_go",
    "slim": "_slim",
    "slugignore": "_config",
    "smarty.tpl": "_smarty",
    "sol": "_ethereum",
    "soql": "_db_1",
    "spec.cjs": "_javascript_1",
    "spec.js": "_javascript_1",
    "spec.jsx": "_react_1",
    "spec.mjs": "_javascript_1",
    "spec.ts": "_typescript_1",
    "spec.tsx": "_react_1",
    "springbeans": "_spring",
    "sss": "_css",
    "stache": "_mustache",
    "static": "_config",
    "stl": "_svg_1",
    "styl": "_stylus",
    "stylelintignore": "_stylelint_1",
    "stylelintrc": "_stylelint",
    "stylelintrc.js": "_stylelint",
    "stylelintrc.json": "_stylelint",
    "stylelintrc.yaml": "_stylelint",
    "stylelintrc.yml": "_stylelint",
    "sublime-project": "_sublime",
    "sublime-workspace": "_sublime",
    "svelte": "_svelte",
    "svg": "_svg",
    "svgx": "_image",
    "test.cjs": "_javascript_1",
    "test.js": "_javascript_1",
    "test.jsx": "_react_1",
    "test.mjs": "_javascript_1",
    "test.ts": "_typescript_1",
    "test.tsx": "_react_1",
    "tf": "_terraform",
    "tf.json": "_terraform",
    "tfvars": "_terraform",
    "tfvars.json": "_terraform",
    "tiff": "_image",
    "tmp": "_clock_1",
    "toml": "_config",
    "tpl": "_smarty",
    "tres": "_godot_2",
    "tscn": "_godot_3",
    "ttf": "_font",
    "twig": "_twig",
    "vala": "_vala",
    "vapi": "_vala",
    "vue": "_vue",
    "wasm": "_wasm",
    "wat": "_wat",
    "wav": "_audio",
    "webm": "_video",
    "webp": "_image",
    "wgt": "_wgt",
    "woff": "_font",
    "woff2": "_font",
    "workspace": "_bazel",
    "xls": "_xls",
    "xlsx": "_xls",
    "zig": "_zig",
    "zip": "_zip_1",
};

// ファイル名そのもの(小文字) -> アイコンID(VS Code本体のfileNames)
export const SETI_FILE_NAMES: Record<string, string> = {
    "babel.config.cjs": "_babel",
    "babel.config.js": "_babel",
    "babel.config.json": "_babel",
    "bower.json": "_bower",
    "build": "_bazel",
    "build.bazel": "_bazel",
    "changelog": "_clock",
    "changelog.md": "_clock",
    "changelog.txt": "_clock",
    "changes": "_clock",
    "changes.md": "_clock",
    "changes.txt": "_clock",
    "cmakelists.txt": "_makefile_3",
    "compiling": "_license_1",
    "compiling.md": "_license_1",
    "compiling.txt": "_license_1",
    "contributing": "_license_2",
    "contributing.md": "_license_2",
    "contributing.txt": "_license_2",
    "copying": "_license",
    "copying.md": "_license",
    "copying.txt": "_license",
    "docker-healthcheck": "_docker_2",
    "eslint.config.js": "_eslint",
    "firebase.json": "_firebase",
    "geckodriver": "_firefox",
    "gruntfile.babel.js": "_grunt",
    "gruntfile.coffee": "_grunt",
    "gruntfile.js": "_grunt",
    "gulpfile": "_gulp",
    "gulpfile.js": "_gulp",
    "ionic.config.json": "_ionic",
    "ionic.project": "_ionic",
    "jenkinsfile": "_jenkins",
    "karma.conf.cjs": "_karma",
    "karma.conf.coffee": "_karma",
    "karma.conf.js": "_karma",
    "karma.conf.mjs": "_karma",
    "licence": "_license",
    "licence.md": "_license",
    "licence.txt": "_license",
    "license": "_license",
    "license.md": "_license",
    "license.txt": "_license",
    "mime.types": "_config",
    "mix": "_hex",
    "mvnw": "_maven",
    "npm-debug.log": "_npm_ignored",
    "omakefile": "_makefile_2",
    "platformio.ini": "_platformio",
    "pom.xml": "_maven",
    "procfile": "_heroku",
    "qmakefile": "_makefile_1",
    "readme": "_info",
    "readme.md": "_info",
    "readme.txt": "_info",
    "rollup.config.js": "_rollup",
    "sass-lint.yml": "_sass",
    "stylelint.config.cjs": "_stylelint",
    "stylelint.config.js": "_stylelint",
    "stylelint.config.mjs": "_stylelint",
    "swagger.json": "_json_1",
    "swagger.yaml": "_json_1",
    "swagger.yml": "_json_1",
    "todo": "_todo",
    "todo.md": "_todo",
    "todo.txt": "_todo",
    "tsconfig.json": "_tsconfig",
    "version": "_clock",
    "version.md": "_clock",
    "version.txt": "_clock",
    "vite.config.cjs": "_vite",
    "vite.config.cts": "_vite",
    "vite.config.js": "_vite",
    "vite.config.mjs": "_vite",
    "vite.config.mts": "_vite",
    "vite.config.ts": "_vite",
    "webpack.common.cjs": "_webpack",
    "webpack.common.js": "_webpack",
    "webpack.common.mjs": "_webpack",
    "webpack.common.ts": "_webpack",
    "webpack.config.build.cjs": "_webpack",
    "webpack.config.build.js": "_webpack",
    "webpack.config.build.mjs": "_webpack",
    "webpack.config.build.ts": "_webpack",
    "webpack.config.cjs": "_webpack",
    "webpack.config.js": "_webpack",
    "webpack.config.mjs": "_webpack",
    "webpack.config.ts": "_webpack",
    "webpack.dev.cjs": "_webpack",
    "webpack.dev.js": "_webpack",
    "webpack.dev.mjs": "_webpack",
    "webpack.dev.ts": "_webpack",
    "webpack.prod.cjs": "_webpack",
    "webpack.prod.js": "_webpack",
    "webpack.prod.mjs": "_webpack",
    "webpack.prod.ts": "_webpack",
    "workspace": "_bazel",
    "workspace.bazel": "_bazel",
    "yarn.clean": "_yarn",
    "yarn.lock": "_yarn",
};

// VS Code本体のtheme-seti JSONには無いが、実際のVS Code既定インストールでは
// (Docker/Git/Make等、標準同梱の言語拡張機能側のファイル名パターンによって)
// 特定のSetiアイコンが表示されるファイル名。
export const SETI_EXTRA_FILE_NAMES: Record<string, string> = {
    ".gitignore": "_git",
    ".gitkeep": "_git",
    ".gitmodules": "_git",
    "dockerfile": "_docker",
    "gnumakefile": "_makefile",
    "makefile": "_makefile",
};

// 拡張子 -> アイコンID(冒頭のコメント参照 - languageId経由でしか解決
// されないメジャーな拡張子を補うテーブル。SETI_FILE_EXTENSIONSで見つから
// なかった場合の次点として参照する)。
export const SETI_EXTENSION_TO_ICON_VIA_LANGUAGE: Record<string, string> = {
    "bash": "_shell",
    "bat": "_windows",
    "c": "_c",
    "cc": "_cpp",
    "cfg": "_config",
    "cjs": "_javascript",
    "clj": "_clojure",
    "cljc": "_clojure",
    "cljs": "_clojure",
    "cmd": "_windows",
    "coffee": "_coffee",
    "cpp": "_cpp",
    "cs": "_c-sharp",
    "css": "_css",
    "csx": "_c-sharp",
    "cts": "_typescript",
    "cxx": "_cpp",
    "dart": "_dart",
    "go": "_go2",
    "groovy": "_grails",
    "htm": "_html_3",
    "html": "_html_3",
    "ini": "_config",
    "java": "_java",
    "jl": "_julia",
    "js": "_javascript",
    "json": "_json",
    "jsonc": "_json",
    "jsonl": "_json",
    "jsx": "_react",
    "less": "_less",
    "lua": "_lua",
    "m": "_c_2",
    "markdown": "_markdown",
    "md": "_markdown",
    "mjs": "_javascript",
    "mm": "_cpp_2",
    "mts": "_typescript",
    "php": "_php",
    "pl": "_perl",
    "pm": "_perl",
    "properties": "_config",
    "ps1": "_powershell",
    "psd1": "_powershell",
    "psm1": "_powershell",
    "py": "_python",
    "pyi": "_python",
    "pyw": "_python",
    "rb": "_ruby",
    "rs": "_rust",
    "scss": "_sass",
    "sh": "_shell",
    "sql": "_db",
    "swift": "_swift",
    "tex": "_tex_1",
    "ts": "_typescript",
    "tsx": "_react",
    "xml": "_xml",
    "yaml": "_yml",
    "yml": "_yml",
    "zsh": "_shell",
};
